Ponder.registry((event) => {
    event.create(["cti:quantum_miner","cti:quantum_miner_advanced"])
        .scene("kubejs:quantum_miner", "位面采矿机", "kubejs:quantum_miner", (scene, utils) => {
        scene.showBasePlate()
        scene.world.showSection([2, 1, 3, 4, 1, 3], Direction.DOWN)
        scene.text(30, "位面采矿机的原理很简单：你给我压缩奇点，我给你矿物")
        scene.idle(30)
        scene.idle(15)
        scene.text(30, "两种采矿机仅在采掘速度与采矿量上有所分别")
        scene.idle(30)
        scene.idle(15)
        scene.addKeyframe()
        scene.rotateCameraY(-180)
        scene.idle(15)
        scene.world.showSection([2, 1, 4, 4, 1, 6], Direction.DOWN)
        scene.text(30, "由于没有GUI，奇点只能由自动化设备输入", [3.5,1.5,5.5])
        scene.idle(30)
        scene.idle(15)
        scene.rotateCameraY(-180)
        scene.world.showSection([2, 2, 3, 4, 2, 3], Direction.DOWN)
        scene.text(30, "之后在采矿机上方放上容器，然后通电即可", [3.5,1.5,2.5])
        scene.idle(10)
        scene.world.showSection([2, 1, 2, 4, 1, 2], Direction.DOWN)
        scene.idle(30)
    })
})
///setblock 2271 72 1210 pipez:gas_pipe[down=false,east=true,has_data=false,north=false,south=false,up=false,waterlogged=false,west=true]