Ponder.registry((event) => {
    event.create("cti:sodium_cooler")
        .scene("kubejs:sodium_cooler", "微型裂变反应堆", "kubejs:sodium_cooler", (scene, utils) => {
        scene.showBasePlate()
        scene.idle(5)
        scene.world.showSection([3, 1, 3], Direction.DOWN)
        scene.idle(5)
        scene.text(30, "微型裂变反应堆是一种安全的裂变装置，该装置完美解决了mek裂变占地面积大、设计复杂且有炸堆风险的问题", [3.5,1.5,3.5])
        scene.idle(30)
        scene.idle(15)
        scene.text(30, "它可以从左侧的气体容器中输入燃料并将废料输出到右侧的气体容器中", [3.5,1.5,3.5])
        scene.idle(30)
        scene.idle(15)
        scene.addKeyframe()
        scene.text(125, "以下方块属于气体容器：", [3.5,1.5,3.5])
        scene.idle(20)
        scene.idle(15)
        scene.world.showSection([1, 1, 1], Direction.DOWN)
        scene.text(20, "化学品储罐", [1.5,1.5,1.5])
        scene.idle(20)
        scene.idle(15)
        scene.world.setBlocks([1, 1, 1], "mekanism:ultimate_pressurized_tube",false)
        scene.text(20, "加压管道", [1.5,1.5,1.5])
        scene.idle(20)
        scene.idle(15)
        scene.world.setBlocks([1, 1, 1], "ae2:interface",false)
        scene.text(20, "以及AE2的ME接口", [1.5,1.5,1.5])
        scene.idle(20)
        scene.idle(15)
        scene.world.setBlocks([1, 1, 1], "minecraft:air",false)
        scene.text(30, "由于技术原因，mek的管道无法在思索界面展示连接材质，我们会尽量减少mek管道的出现")
        scene.idle(30)
        scene.idle(15)
        scene.world.showSection([6, 1, 3, 4, 1, 3], Direction.DOWN)
        scene.addKeyframe()
        scene.text(20, "裂变燃料从左侧注入", [5.5,1.5,3.5])
        scene.idle(20)
        scene.idle(15)
        scene.world.showSection([2, 1, 3, 0, 1, 3], Direction.DOWN)
        scene.text(20, "核废料从右侧输出", [1.5,1.5,3.5])
        scene.idle(20)
        scene.idle(15)
        scene.text(30, "之后连接任意面输出能量即可")
        scene.idle(30)
        scene.idle(15)
        scene.addKeyframe()
        scene.world.showSection([3, 2, 3, 3, 6, 3], Direction.DOWN)
        scene.text(20, "答应我，别这么做好吗", [3.5,3.5,3.5])
        scene.idle(20)
        scene.idle(15)
        scene.text(30, "裂变堆的产出效率不是pipez的管道可以承受的", [3.5,3.5,3.5])
        scene.idle(30)
        scene.idle(15)
        scene.addKeyframe()
        scene.world.setBlocks([3, 6, 3, 3, 3, 3], "minecraft:air",true)
        scene.world.setBlocks([3, 2, 3], "mekaevolution:infinite_universal_cable",true)
        scene.text(20, "mekaevolution的无限能量管道", [3.5,2.5,3.5])
        scene.idle(20)
        scene.idle(15)
        scene.world.setBlocks([3, 2, 3], "fluxnetworks:flux_plug",true)
        scene.world.modifyBlock([3, 2, 3], (state) => state.with("down", "true"), false)
        scene.text(30, "或是直接接入通量网络才是更好的选择", [3.5,2.5,3.5])
        scene.idle(30)
        scene.idle(15)
        scene.text(30, "需要注意的是右侧首位不能使用储罐，否则会导致核废料丢失", [2.5,1.5,3.5])
        scene.addKeyframe()
        scene.idle(30)
        scene.idle(15)
        scene.world.setBlocks([1, 1, 3, 0, 1, 3], "ae2:cable_bus",true)
        scene.world.setBlocks([2, 1, 3], "ae2:interface",true)
        scene.world.modifyTileNBT([1,1,3,0,1,3],nbt => {
            nbt.cable = {
                id: "ae2:fluix_covered_cable",
                visual: {
                    connections: ["east","west"]
                }
            }
        },true)
        scene.text(40, "当然，你也可以试试这个结构", [2.5,1.5,3.5])
        scene.idle(40)
    })
})
///setblock 2268 72 1203 ae2:cable_bus[light_level=0,waterlogged=false]{ForgeCaps:{},cable:{gn:{g:0L,k:-1L,p:0},id:"ae2:fluix_covered_cable"},hasRedstone:2}