StartupEvents.registry("item",event=>{
    event.create("ultra_dense_nugget","basic")
    event.create("overchargedultradense","basic")
    event.create("protonium_nugget","basic")
    event.create("gas_hydrate","basic")
    event.create("graphene","basic")
    event.create("dusts_titanium","basic")
    event.create("tungsten_ingot","basic")
    event.create("halfdone_exoalloy","basic")
    event.create("pyrocrystal","basic")
    event.create("electrocrystal","basic")
    event.create("violium_alloy","basic")
    event.create("activated_matter_dust","basic")
    event.create("neutronium_singularity_press","basic").tag('thermal:crafting/dies')
    event.create("atherium_alloy","basic")
    event.create("ultra_dense_hydride_crystal","basic")
    event.create("particle_container","basic")
    event.create("clock_core","basic")
    event.create("living_control_circuit","basic")
    event.create("thermite","basic")
    event.create("unfinished_advanced_dyano_augment","basic")
    event.create("unfinished_advanced_output_augment","basic")
    event.create("unfinished_advanced_speed_augment","basic")
    event.create("universal_press","basic")
    event.create("phytogro_zero","basic")
    event.create("ancient_circuitboard","basic")
    event.create("enriched_refined_glowstone","basic")
    event.create("uncomplete_upgrade_augment_6","basic")
    event.create("disintegrate_crystal","basic")
    event.create("cnt","basic")

    

    event.create("dense_slag","basic")
    event.create("crystal_slag","basic")
    event.create("enriched_slag","basic")
    event.create("metal_slag","basic")
    event.create("stable_slag","basic")
    event.create("light_slag","basic")
    event.create("mineral_slag","basic")
    event.create("powdered_slag","basic")

    event.create("core_basic","basic")
    event.create("core_blaze","basic")
    event.create("core_diamond","basic")
    event.create("core_emerald","basic")
    event.create("core_harden","basic")
    event.create("core_nether","basic")

    event.create("aetherium_core","basic")
    event.create("violium_core","basic")

    event.create("dust_mana","basic")
    event.create("dust_cryotheum","basic")
    event.create("dust_pyrotheum","basic")
    event.create("dust_petrotheum","basic")

    event.create("crystal_ender","basic")
    event.create("crystal_glowstone","basic")
    event.create("crystal_redstone","basic")

    event.create("empty_record","basic")
    event.create("cosmic_mechanism","basic")
    event.create("electro_magnetic_mechanism","basic")
    event.create("energy_mechanism","basic")
    event.create("gravity_mechanism","basic")
    event.create("singnal_mechanism","basic")
    event.create("structre_mechanism","basic")
    event.create("tungsten_steel_ingot","basic")
    event.create("evil_mechanism","basic")
    event.create("pure_silicon","basic")
    event.create("meteorium_scrap","basic")
    event.create("meteorium_ingot","basic")
    event.create("aetheric_thermite","basic")
    event.create("broken_victory_medal","basic")
    event.create("phoenix_ingot","basic")
    event.create("valkyrie_ingot","basic")

    event.create("luminous_metal_plate","basic")
    event.create("radient_engine","basic")

    event.create("dielectric_paste_1","basic")
    event.create("dielectric_paste_2","basic")
    event.create("dielectric_paste_3","basic")
    event.create("dielectric_paste_4","basic")
    event.create("dielectric_paste_5","basic")
    event.create("dielectric_paste_6","basic")

    event.create("sentrite","basic")
    event.create("pneumatic_shield","basic")
    event.create("carbon_plate","basic")
    event.create("life_crystal","basic")
    event.create("evil_processor","basic")
})