JEIEvents.information(event => {
event.addItem('lightmanscurrency:coinmint', Text.black({ "translate": "kubejs.jei.coinmint" }))
event.addItem('twilightforest:uncrafting_table', Text.black({ "translate": "kubejs.jei.uncrafting_table" }))
event.addItem('projecte:transmutation_table', Text.black({ "translate": "kubejs.jei.transmutation_table" }))
event.addItem('projecte:transmutation_tablet', Text.black({ "translate": "kubejs.jei.transmutation_tablet" }))
event.addItem('tinkerscalibration:moonsteel_ingot', Text.black({ "translate": "kubejs.jei.moonsteel_ingot" }))
event.addFluid('manaliquidizer:mana_fluid', Text.black({ "translate": "kubejs.jei.mana_fluid" }))
event.addFluid('kubejs:hot_heavymetal_lava', Text.black({ "translate": "kubejs.jei.hot_heavymetal_lava" }))
event.addFluid('kubejs:royal_jelly', Text.black({ "translate": "kubejs.jei.royal_jelly" }))
event.addFluid('kubejs:hot_heavycrystal_lava', Text.black({ "translate": "kubejs.jei.hot_heavycrystal_lava" }))
event.addItem('immersiveengineering:railgun', Text.black({ "translate": "kubejs.jei.railgun" }))

event.addItem('tinkers_ingenuity:splendid_ingot', Text.black({ "translate": "kubejs.jei.glorious_seal" }))
event.addItem('bigger_ae2:4_core_crafting_accelerator', Text.black({ "translate": "kubejs.jei.accelerator" }))
event.addItem('bigger_ae2:16_core_crafting_accelerator', Text.black({ "translate": "kubejs.jei.accelerator" }))
event.addItem('bigger_ae2:64_core_crafting_accelerator', Text.black({ "translate": "kubejs.jei.accelerator" }))
event.addItem('bigger_ae2:256_core_crafting_accelerator', Text.black({ "translate": "kubejs.jei.accelerator" }))
event.addItem('bigger_ae2:1024_core_crafting_accelerator', Text.black({ "translate": "kubejs.jei.accelerator" }))
event.addItem('cti:fracture_silicon', Text.black({ "translate": "kubejs.jei.fracture_silicon" }))
event.addItem('cti:fracture_silicon_budding', Text.black({ "translate": "kubejs.jei.fracture_silicon" }))
event.addItem('cti:rasterite', Text.black({ "translate": "kubejs.jei.rasterite" }))
event.addItem('cti:rasterite_budding', Text.black({ "translate": "kubejs.jei.rasterite" }))
event.addItem('cti:unipolar_magnet', Text.black({ "translate": "kubejs.jei.unipolar_magnet" }))
event.addItem('cti:unipolar_magnet_budding', Text.black({ "translate": "kubejs.jei.unipolar_magnet" }))
event.addItem('kubejs:aetherium_core', Text.black({ "translate": "kubejs.jei.aetherium_core" }))
event.addItem('kubejs:violium_core', Text.black({ "translate": "kubejs.jei.violium_core" }))
event.addItem('obscure_api:astral_dust', Text.black({ "translate": "kubejs.jei.astral_dusttt" }))
})

