Ponder.registry((event) => {
    event.create(["mekanismgenerators:fission_reactor_casing","mekanismgenerators:fisson_reactor_logic_adapter","mekanismgenerators:control_rod_assembly","mekanismgenerators:fission_fuel_assembly","mekanismgenerators:fission_reactor_port","mekanismgenerators:reactor_glass"])
        .scene("kubejs:fission_reactor1", "裂变反应堆的构造原理", "kubejs:fission_reactor", (scene, utils) => {
            scene.scaleSceneView(0.6)
            scene.showStructure(0)

            for(let y = 1; y < 14; y++){
                scene.world.showSection([8,y,4,4,y,8],Direction.DOWN)
                scene.idle(7)
            }

            scene.text(30, "如图所示是一个标准的5×8×5反应堆")
            scene.idle(45)
            // scene.text(30, "接下来我将在多个情景中为你讲解它的构造原理、建筑规模与自动化方式")
            // scene.idle(45)
            // scene.text(30, "第一个情景，让我们从基础构造原理与建筑须知开始")
            // scene.idle(45)
            scene.addKeyframe()
            scene.world.hideSection([4,1,4,8,8,8],Direction.UP)
            scene.text(40, "裂变堆由两部分组成")
            scene.idle(65)
            scene.text(40, "一个外壳")
            scene.world.showSection([4,1,4,8,1,8],Direction.DOWN)
            scene.idle(5)
            scene.world.showSection([4,2,4,4,7,8],Direction.DOWN)
            scene.world.showSection([8,2,4,8,7,8],Direction.DOWN)
            scene.world.showSection([7,2,4,5,7,4],Direction.DOWN)
            scene.world.showSection([7,2,8,5,7,8],Direction.DOWN)
            scene.idle(5)
            scene.world.showSection([4,8,4,8,8,8],Direction.DOWN)
            scene.idle(35)
            scene.idle(20)
            scene.world.hideSection([4,1,4,8,1,8],Direction.DOWN)
            scene.world.hideSection([4,2,4,4,7,8],Direction.WEST)
            scene.world.hideSection([8,2,4,8,7,8],Direction.EAST)
            scene.world.hideSection([7,2,4,5,7,4],Direction.NORTH)
            scene.world.hideSection([7,2,8,5,7,8],Direction.SOUTH)
            scene.world.hideSection([4,8,4,8,8,8],Direction.UP)
            scene.idle(15)
            scene.text(40, "以及装载在里面的燃料棒组件")
            scene.world.showSection([7,2,5,7,7,5],Direction.DOWN)
            scene.idle(5)
            scene.world.showSection([5,2,5,5,7,5],Direction.DOWN)
            scene.idle(5)
            scene.world.showSection([6,2,6,6,7,6],Direction.DOWN)
            scene.idle(5)
            scene.world.showSection([7,2,7,7,7,7],Direction.DOWN)
            scene.idle(5)
            scene.world.showSection([5,2,7,5,7,7],Direction.DOWN)
            scene.idle(35)
            scene.addKeyframe()
            scene.world.hideSection([7,2,5,7,7,5],Direction.UP)
            scene.world.hideSection([5,2,5,5,7,5],Direction.UP)
            scene.world.hideSection([6,2,6,6,7,6],Direction.UP)
            scene.world.hideSection([7,2,7,7,7,7],Direction.UP)
            scene.world.hideSection([5,2,7,5,7,7],Direction.UP)
            scene.idle(15)
            scene.text(20, "其中，外壳的构造有如下需求：")
            scene.world.showSection([4,1,4,8,1,8],Direction.UP)
            scene.world.showSection([4,2,4,4,7,8],Direction.EAST)
            scene.world.showSection([8,2,4,8,7,8],Direction.WEST)
            scene.world.showSection([7,2,4,5,7,4],Direction.SOUTH)
            scene.world.showSection([7,2,8,5,7,8],Direction.NORTH)
            scene.world.showSection([4,8,4,8,8,8],Direction.DOWN)
            scene.idle(35)
            scene.text(40, "边框与底部§9只能§r由反应堆外壳方块搭建")
            scene.overlay.showOutline("red", {}, [4, 1, 4, 8, 1, 8], 30)
            scene.overlay.showOutline("red", {}, [4, 1, 4, 4, 8, 4], 30)
            scene.overlay.showOutline("red", {}, [8, 1, 4, 8, 8, 4], 30)
            scene.overlay.showOutline("red", {}, [4, 1, 8, 4, 8, 8], 30)
            scene.overlay.showOutline("red", {}, [8, 1, 8, 8, 8, 8], 30)
            scene.overlay.showOutline("red", {}, [8, 8, 8, 4, 8, 8], 30)
            scene.overlay.showOutline("red", {}, [8, 8, 4, 4, 8, 4], 30)
            scene.overlay.showOutline("red", {}, [8, 8, 4, 8, 8, 8], 30)
            scene.overlay.showOutline("red", {}, [4, 8, 4, 4, 8, 8], 30)
            scene.idle(65)
            scene.addKeyframe()
            scene.text(40, "侧面与顶层可以使用强化玻璃、外壳和端口中的任意一种")
            scene.overlay.showOutline("green", {}, [7, 2, 4, 5, 7, 4], 40)
            scene.overlay.showOutline("green", {}, [4, 2, 5, 4, 7, 7], 40)
            scene.overlay.showOutline("green", {}, [7, 2, 8, 5, 7, 8], 40)
            scene.overlay.showOutline("green", {}, [8, 2, 5, 8, 7, 7], 40)
            scene.overlay.showOutline("green", {}, [5, 8, 5, 7, 8, 7], 40)
            scene.idle(55)
            // scene.text(30, "关于端口的使用方式，请允许我在两个情景后再作讲解")
            // scene.idle(45)
            scene.addKeyframe()
            scene.text(40, "裂变反应堆的外壳尺寸允许3×3×4到18×18×18的任意尺寸")
            scene.idle(65)
            scene.text(40, "尺寸越大，冷却液箱与其加热产物的缓存越大")
            scene.idle(65)
            scene.addKeyframe()
            scene.world.hideSection([4,2,4,4,7,8],Direction.WEST)
            scene.world.hideSection([8,2,4,8,7,8],Direction.EAST)
            scene.world.hideSection([7,2,4,5,7,4],Direction.NORTH)
            scene.world.hideSection([7,2,8,5,7,8],Direction.SOUTH)
            scene.world.hideSection([4,8,4,8,8,8],Direction.UP)
            scene.idle(15)
            scene.text(40, "燃料棒的构造需求如下：")
            scene.world.showSection([7,2,5,7,7,5],Direction.DOWN)
            scene.world.showSection([5,2,5,5,7,5],Direction.DOWN)
            scene.world.showSection([6,2,6,6,7,6],Direction.DOWN)
            scene.world.showSection([7,2,7,7,7,7],Direction.DOWN)
            scene.world.showSection([5,2,7,5,7,7],Direction.DOWN)
            scene.idle(55)
            scene.text(40, "1.燃料棒由列式的裂变燃料组件与顶端的控制棒组件构成")
            scene.overlay.showOutline("red", {}, [5, 2, 5, 5, 6, 5], 30)
            scene.overlay.showOutline("red", {}, [5, 2, 7, 5, 6, 7], 30)
            scene.overlay.showOutline("red", {}, [6, 2, 6, 6, 6, 6], 30)
            scene.overlay.showOutline("red", {}, [7, 2, 5, 7, 6, 5], 30)
            scene.overlay.showOutline("red", {}, [7, 2, 7, 7, 6, 7], 30)
            scene.overlay.showOutline("green", {}, [5, 7, 5], 30)
            scene.overlay.showOutline("green", {}, [5, 7, 7], 30)
            scene.overlay.showOutline("green", {}, [6, 7, 6], 30)
            scene.overlay.showOutline("green", {}, [7, 7, 5], 30)
            scene.overlay.showOutline("green", {}, [7, 7, 7], 30)
            scene.idle(55)
            scene.text(40, "其中，燃料棒可以悬空，但顶端必须有控制棒组件")
            scene.world.setBlocks([5,2,5], "minecraft:air",true)
            scene.world.setBlocks([7,7,5], "minecraft:air",true)
            scene.overlay.showOutline("green", {}, [5,3,5,5,7,5], 30)
            scene.overlay.showOutline("red", {}, [7,2,5,7,6,5], 30)
            scene.idle(55)
            scene.world.setBlocks([5,2,5], "mekanismgenerators:fission_fuel_assembly",true)
            scene.world.setBlocks([7,7,5], "mekanismgenerators:control_rod_assembly",true)
            scene.idle(5)
            scene.addKeyframe()
            scene.text(40, "2.燃料棒的摆放方式关系到反应堆的沸腾效率，表面积越大，沸腾效率越高（最大为1）")
            scene.idle(55)
            scene.text(60, "§9类国际象棋棋盘的摆法§r是沸腾效率最高时的密铺摆法")
            scene.overlay.showOutline("green", {}, [6, 2, 5, 6, 7, 5], 50)
            scene.overlay.showOutline("green", {}, [5, 7, 6, 5, 2, 6], 50)
            scene.overlay.showOutline("green", {}, [7, 7, 6, 7, 2, 6], 50)
            scene.overlay.showOutline("green", {}, [6, 7, 7, 6, 2, 7], 50)
            scene.idle(75)
            scene.text(40, "不建议采用完全密铺式摆件")
            scene.world.setBlocks([6,2,5,6,6,5], "mekanismgenerators:fission_fuel_assembly",true)
            scene.world.setBlocks([5,6,6,5,2,6], "mekanismgenerators:fission_fuel_assembly",true)
            scene.world.setBlocks([7,6,6,7,2,6], "mekanismgenerators:fission_fuel_assembly",true)
            scene.world.setBlocks([6,6,7,6,2,7], "mekanismgenerators:fission_fuel_assembly",true)
            scene.world.setBlocks([6,7,5], "mekanismgenerators:control_rod_assembly",true)
            scene.world.setBlocks([5,7,6], "mekanismgenerators:control_rod_assembly",true)
            scene.world.setBlocks([7,7,6], "mekanismgenerators:control_rod_assembly",true)
            scene.world.setBlocks([6,7,7], "mekanismgenerators:control_rod_assembly",true)
            scene.world.showSection([6, 2, 5, 6, 7, 5],Direction.DOWN)
            scene.world.showSection([5, 7, 6, 5, 2, 6],Direction.DOWN)
            scene.world.showSection([7, 7, 6, 7, 2, 6],Direction.DOWN)
            scene.world.showSection([6, 7, 7, 6, 2, 7],Direction.DOWN)
            scene.overlay.showOutline("red", {}, [6, 2, 5, 6, 7, 5], 140)
            scene.overlay.showOutline("red", {}, [5, 7, 6, 5, 2, 6], 140)
            scene.overlay.showOutline("red", {}, [7, 7, 6, 7, 2, 6], 140)
            scene.overlay.showOutline("red", {}, [6, 7, 7, 6, 2, 7], 140)
            scene.idle(45)
            scene.text(60, "这会导致沸腾效率降低、蒸汽产量减少、冷却效率降低")
            scene.idle(45)
            // scene.text(60, "考虑到外壳较为低廉的造价，可能你另外再造一个或是扩大外壳尺寸是个更好的选择")
            // scene.idle(75)
            scene.world.setBlocks([6, 2, 5, 6, 7, 5], "minecraft:air",true)
            scene.world.setBlocks([5, 7, 6, 5, 2, 6], "minecraft:air",true)
            scene.world.setBlocks([7, 7, 6, 7, 2, 6], "minecraft:air",true)
            scene.world.setBlocks([6, 7, 7, 6, 2, 7], "minecraft:air",true)
            scene.idle(15)
    })
    // event.create(["mekanismgenerators:fission_reactor_casing","mekanismgenerators:control_rod_assembly","mekanismgenerators:fission_fuel_assembly","mekanismgenerators:fission_reactor_port","mekanismgenerators:reactor_glass"])
    //     .scene("kubejs:fission_reactor2", "最大的裂变反应堆", "kubejs:fission_reactor_max", (scene, utils) => {
    //         scene.scaleSceneView(0.25)
    //         scene.showStructure(18)
    //         scene.text(30, "第二个情景展示了最大的18×18×18反应堆，这里可以做一个参考")
    //         scene.idle(45)
    // })
    event.create(["mekanismgenerators:fission_reactor_casing","mekanismgenerators:fisson_reactor_logic_adapter","mekanismgenerators:control_rod_assembly","mekanismgenerators:fission_fuel_assembly","mekanismgenerators:fission_reactor_port","mekanismgenerators:reactor_glass"])
        .scene("kubejs:fission_reactor3", "裂变反应堆的自动化", "kubejs:fission_reactor_auto", (scene, utils) => {
            scene.scaleSceneView(0.6)
            scene.world.setBlocks([5,2,4], "mekanismgenerators:reactor_glass",false)
            scene.world.setBlocks([7,2,4], "mekanismgenerators:reactor_glass",false)
            scene.world.setBlocks([4,2,6], "mekanismgenerators:reactor_glass",false)
            scene.world.setBlocks([8,2,6], "mekanismgenerators:reactor_glass",false)
            scene.showStructure(0)
            scene.world.showSection([4,1,4,8,8,8],Direction.DOWN)
            // scene.text(30, "第三个情景，裂变反应堆的自动化")
            // scene.idle(45)
            scene.text(60, "mek的裂变反应堆§9本身并没有发电能力§r，主要通过对冷却剂的处理来发电")
            scene.idle(75)
            // scene.text(30, "此外，由于技术原因，mek的管道无法在思索界面展示连接材质，我们会尽量减少mek管道的出现")
            // scene.idle(45)
            scene.text(60, "由于mek适配问题，思索展示存在bug，我们将尽量减少mek管道的出现")
            scene.idle(75)
            scene.addKeyframe()
            scene.world.setBlocks([6,2,4], "mekanismgenerators:fission_reactor_port",true)
            scene.text(40, "裂变堆通过反应堆端口与外界交互",[6.5,2.5,4])
            scene.idle(65)
            scene.text(40, "使用配置器潜行+右键切换端口的模式",[6.5,2.5,4])
            scene.showControls(150, [6.5,2.5,4], "up")
                .rightClick()
                .withItem("mekanism:configurator")
                .whileSneaking()
            scene.idle(65)
            scene.text(20, "共有三个模式",[6.5,2.5,4])
            scene.idle(35)
            scene.text(20, "仅输入",[6.5,2.5,4])
            scene.idle(25)
            scene.world.modifyBlock([6,2,4], (state) => state.with("mode", "output_waste"), false)
            scene.text(20, "废料输出",[6.5,2.5,4])
            scene.idle(25)
            scene.world.modifyBlock([6,2,4], (state) => state.with("mode", "output_coolant"), false)
            scene.text(20, "热冷却剂输出",[6.5,2.5,4])
            scene.idle(35)
            scene.addKeyframe()
            scene.world.setBlocks([6,2,4], "mekanismgenerators:reactor_glass",true)
            scene.world.setBlocks([5,2,4], "mekanismgenerators:fission_reactor_port",true)
            scene.world.setBlocks([7,2,4], "mekanismgenerators:fission_reactor_port",true)
            scene.world.setBlocks([4,2,6], "mekanismgenerators:fission_reactor_port",true)
            scene.world.setBlocks([8,2,6], "mekanismgenerators:fission_reactor_port",true)
            scene.world.modifyBlock([4,2,6], (state) => state.with("mode", "output_coolant"), false)
            scene.world.modifyBlock([8,2,6], (state) => state.with("mode", "output_waste"), false)
            scene.text(40, "因此，裂变堆的自动化至少需要四个端口")
            scene.rotateCameraY(90)
            scene.idle(20)
            scene.rotateCameraY(-90)
            scene.idle(25)
            scene.text(20, "供给冷却剂",[5.5,2.5,3.5])
            scene.world.showSection([5,2,3,5,2,0],Direction.SOUTH)
            scene.idle(35)
            scene.text(20, "供给裂变燃料",[7.5,2.5,3.5])
            scene.world.showSection([7,2,3,7,2,0],Direction.SOUTH)
            scene.idle(35)
            scene.text(20, "输出热冷却剂",[3.5,2.5,6.5])
            scene.world.showSection([3,2,6,0,2,6],Direction.WEST)
            scene.idle(35)
            scene.rotateCameraY(90)
            scene.text(20, "输出核废料",[9.5,2.5,6.5])
            scene.world.showSection([9,2,6,12,2,6],Direction.EAST)
            scene.idle(35)
            scene.rotateCameraY(-90)
            scene.text(60, "在配置好后就可以激活反应堆了，速率调节在gui左上角的信息栏里\n§9祝好运 :) §r")
            scene.idle(75)
    })
//     event.create(["mekanismgenerators:fission_reactor_casing","mekanismgenerators:control_rod_assembly","mekanismgenerators:fission_fuel_assembly","mekanismgenerators:fission_reactor_port","mekanismgenerators:reactor_glass"])
//         .scene("kubejs:fission_reactor4", "水冷与废料处理", "kubejs:fission_reactor_water", (scene, utils) => {
//             scene.scaleSceneView(0.45)
//             scene.showStructure(0)
//             scene.world.showSection([12,9,12,0,1,5],Direction.DOWN)
//             scene.text(30, "第三个情景，水冷反应堆与废料处理")
//             scene.idle(45)
//             scene.text(30, "如图所示便是一个以水为冷却剂的裂变发电单元")
//             scene.idle(45)
//             scene.text(20, "左侧是燃料与水输入",[11.5,2.5,7.5])
//             scene.idle(35)
//             scene.text(20, "右侧是蒸汽涡轮发电单元",[2.5,5,10.5])
//             scene.idle(35)
//             scene.text(20, "前面连接废料处理",[9.5,2.5,7.5])
//             scene.idle(35)
//             scene.text(30, "没错，就是这样，只要掌握了自动化输入输出，水冷基本是手到擒来")
//             scene.idle(45)
//             scene.text(40, "作为代价，水冷的最高功率只有717ml/t，低于钠冷极限的1400+ml/t，不过由于水冷极为简单，其依旧是最流行的裂变配置")
//             scene.idle(55)
//             scene.world.hideSection([0,1,7,7,9,12],Direction.WEST)
//             scene.text(30, "更为关键的是，即使没有蒸汽处理，只要保证水流供应，水冷堆依旧能安全运行")
//             scene.idle(45)
//             scene.world.showSection([0,1,7,7,9,12],Direction.EAST)
//             scene.text(30, "因此，强烈推荐各位使用水冷堆进行初期废料生产")
//             scene.idle(45)
//             scene.addKeyframe()
//             scene.world.showSection([0,1,1,4,5,4],Direction.WEST)
//             scene.world.showSection([12,1,0,8,3,4],Direction.WEST)
//             scene.text(30, "在水冷生产中，可能只有废料处理算是一个难点")
//             scene.idle(45)
//             scene.text(30, "其中最大的一点在于，核废料没有能安全存储的容器，极其容易造成泄漏事件")
//             scene.idle(45)
//             scene.world.setBlocks([0,1,1,4,5,4], "mekanism:ultimate_pressurized_tube",true)
//             scene.text(30, "想要存储放射性物质，唯一的方法是堆叠大量加压管道，因为pipez的管道没有缓存。嗯，mek裂变不得不品的一环")
//             scene.idle(45)
//             scene.world.setBlocks([0,1,1,4,5,4], "minecraft:air",true)
//             scene.text(30, "这里使用pipez管道只是因为前文说到的技术原因")
//             scene.idle(45)
//             scene.addKeyframe()
//             scene.rotateCameraY(75)
//             scene.text(30, "现在，让我们把目光放到废料处理")
//             scene.idle(45)
//             scene.text(30, "在本整合包中，共有三种废料处理的办法")
//             scene.idle(45)
//             scene.overlay.showOutline("green", {}, [12,1,0,10,3,3], 30)
//             scene.text(30, "生产裂变等离子体的加压反应室",[11.5,2.5,2.5])
//             scene.idle(45)
//             scene.overlay.showOutline("green", {}, [9,1,0,9,3,3], 30)
//             scene.text(30, "生产钚的同位素离心机",[9.5,3,2.5])
//             scene.idle(45)
//             scene.overlay.showOutline("green", {}, [8,1,0,8,3,3], 30)
//             scene.text(30, "生产钋的太阳能中子活化器",[8.5,3,2.5])
//             scene.idle(45)
//             scene.overlay.showOutline("red", {}, [12,1,0,11,3,3], 85)
//             scene.text(40, "其中，加压反应室路线成本最高，但也是可以生产裂变等离子体的唯一方法，在开采磁单极石后可以大大加快反物质生产",[11.5,2.5,2.5])
//             scene.idle(55)
//             scene.overlay.showOutline("green", {}, [10,1,0,10,3,3], 30)
//             scene.text(30, "同时，其也可以产出能被氧化为裂变燃料并重新循环的再处理裂变碎片",[10.5,2.5,2.5])
//             scene.idle(45)
//             scene.overlay.showOutline("red", {}, [9,1,0,9,3,3], 75)
//             scene.overlay.showOutline("red", {}, [8,1,0,8,3,3], 75)
//             scene.text(30, "相比之下，钋和钚的生产就要简单得多，只需输入输出即可",[9,3,2.5])
//             scene.idle(45)
//             scene.text(30, "但由于钋和钚本身也是放射性物质，加压管道仍是安全存储的唯一途径",[9,3,2.5])
//             scene.idle(45)
//             scene.addKeyframe()
//             scene.world.showSection([12,4,0,0,7,4],Direction.SOUTH)
//             scene.text(30, "不仅如此，制作钋靶丸与钚靶丸后，还会产生无法利用的放射性用尽核废料",[9.5,5.5,2.5])
//             scene.idle(45)
//             scene.text(30, "不过，反正都加了AE2了......")
//             scene.idle(45)
//             scene.world.showSection([7,1,0,5,3,4],Direction.SOUTH)
//             scene.rotateCameraY(-25)
//             scene.text(30, "我们可以用这样一个结构简单粗暴地删除这个问题",[7,1.5,2.5])
//             scene.idle(45)
//     })
})
///setblock 2273 73 1209 pipez:fluid_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
///setblock 2269 73 1213 pipez:gas_pipe[down=false,east=true,has_data=true,north=false,south=false,up=false,waterlogged=false,west=true]{DisconnectedSides:[0b,0b,0b,0b,0b,0b],ExtractingSides:[0b,0b,0b,0b,0b,1b],ForgeCaps:{},Upgrades:[]}