Ponder.registry((event) => {
	event.create("pneumaticcraft:pressure_chamber_wall")
		.scene("kubejs:pressure_chamber1", "压力室的搭建", "kubejs:yalishi1",(scene, utils) => {
			scene.showBasePlate()
			scene.idle(3)
			scene.text(20, "用压力室墙壁搭建出来5x5(4x4,3x3也可以)的空心结构")
			scene.world.showSection([0, 1, 0, 4, 1, 4], Direction.DOWN)
			scene.idle(3)
			scene.world.showSection([0, 2, 0, 4, 2, 4], Direction.DOWN)
			scene.idle(3)
			scene.world.showSection([0, 3, 0, 4, 3, 4], Direction.DOWN)
			scene.idle(3)
			scene.world.showSection([0, 4, 0, 4, 4, 4], Direction.DOWN)
			scene.idleSeconds(1)
			scene.addKeyframe()
			scene.text(20, "放置压力室接口,一面朝内一面朝外，分别对应输入输出", [0, 2, 1])
			scene.idle(3)
			scene.world.setBlocks([0, 2, 3], 'pneumaticcraft:pressure_chamber_interface',true)
			scene.world.setBlocks([0, 2, 1], 'pneumaticcraft:pressure_chamber_interface',true)
			scene.world.modifyBlock([0, 2, 1], (state) => state.with("facing", "west"), true)
			scene.world.modifyBlock([0, 2, 3], (state) => state.with("facing", "east"), true)
			scene.idleSeconds(1)
			scene.addKeyframe()
			scene.text(20, "墙壁上放置压力室气阀,这里输入压缩空气", [2, 2, 0])
			scene.world.setBlocks([2, 2, 0], 'pneumaticcraft:pressure_chamber_valve',true)
			scene.idleSeconds(1)
			scene.text(20, "此时结构就形成好了", [2, 2, 0])
		})
		.scene("kubejs:pressure_chamber2", "压力室的搭建2 ","kubejs:yalishi2",(scene, utils) => {
			scene.showBasePlate()
			scene.idle(3)
			scene.text(30, "当然你也可以用玻璃，这样更能看清内部") 
			scene.world.showSection([0, 1, 0, 4, 1, 4], Direction.DOWN)
			scene.idle(3)
			scene.world.showSection([0, 2, 0, 4, 2, 4], Direction.DOWN)
			scene.idle(3)
			scene.world.showSection([0, 3, 0, 4, 3, 4], Direction.DOWN)
			scene.idle(3)
			scene.world.showSection([0, 4, 0, 4, 4, 4], Direction.DOWN)
			scene.idleSeconds(1)
        })
})